package pl.inf.app.api;

import lombok.Getter;

@Getter
public enum LinkRelations {
	GET_AUTH_LINKS,
	GET_USER_LINKS,
	GET_ADMIN_LINKS,

	LOGIN,
	LOGOUT,

	REGISTER_USER,
	GET_USER,

	GET_ALL_ACCESSORY_TYPE,
	GET_ACCESSORY_TYPE,
	SAVE_ACCESSORY_TYPE,
	UPDATE_ACCESSORY_TYPE,
	DELETE_ACCESSORY_TYPE,

	GET_ALL_AQUARIUM,
	GET_AQUARIUM,
	GET_USER_AQUARIUM,
	SAVE_AQUARIUM,
	UPDATE_AQUARIUM,
	DELETE_AQUARIUM,

	GET_ALL_AQUARIUM_TEMPLATE,
	GET_AQUARIUM_TEMPLATE,
	SAVE_AQUARIUM_TEMPLATE,
	UPDATE_AQUARIUM_TEMPLATE,
	DELETE_AQUARIUM_TEMPLATE,

	GET_ALL_DECORATOR_TYPE,
	GET_DECORATOR_TYPE,
	SAVE_DECORATOR_TYPE,
	UPDATE_DECORATOR_TYPE,
	DELETE_DECORATOR_TYPE,

	GET_ALL_FISH,
	GET_FISH,
	SAVE_FISH,
	UPDATE_FISH,
	DELETE_FISH,

	GET_ALL_FISH_TYPE,
	GET_FISH_TYPE,
	SAVE_FISH_TYPE,
	UPDATE_FISH_TYPE,
	DELETE_FISH_TYPE,

	GET_ALL_KNOWLEDGE,
	GET_KNOWLEDGE,
	SAVE_KNOWLEDGE,
	UPDATE_KNOWLEDGE,
	DELETE_KNOWLEDGE,

	GET_ALL_PARAMETERS_HISTORY,
	GET_PARAMETERS_HISTORY,
	SAVE_PARAMETERS_HISTORY,
	UPDATE_PARAMETERS_HISTORY,
	DELETE_PARAMETERS_HISTORY
}
