ALTER TABLE accessory_type
    ADD COLUMN "volume" FLOAT NOT NULL DEFAULT 0;

ALTER TABLE knowledge
    ADD COLUMN "min" FLOAT NOT NULL DEFAULT 0;
ALTER TABLE knowledge
    ADD COLUMN "max" FLOAT NOT NULL DEFAULT 0;
